PROVINCE_CODES = {
    '11': 'Cao Bằng',
    '65': 'Cần Thơ',
    '12': 'Lạng Sơn',
    '66': 'Đồng Tháp',
    '14': 'Quảng Ninh',
    '67': 'An Giang',
    '15': 'Hải Phòng',
    '16': 'Hải Phòng',
    '68': 'Kiên Giang',
    '17': 'Thái Bình',
    '69': 'Cà Mau',
    '18': 'Nam Định',
    '70': 'Tây Ninh',
    '19': 'Phú Thọ',
    '71': 'Bến Tre',
    '20': 'Thái Nguyên',
    '72': 'Bà Rịa – Vũng Tàu',
    '21': 'Yên Bái',
    '73': 'Quảng Bình',
    '22': 'Tuyên Quang',
    '74': 'Quảng Trị',
    '23': 'Hà Giang',
    '75': 'Thừa Thiên Huế',
    '24': 'Lào Cai',
    '76': 'Quảng Ngãi',
    '25': 'Lai Châu',
    '77': 'Bình Định',
    '26': 'Sơn La',
    '78': 'Phú Yên',
    '27': 'Điện Biên',
    '79': 'Khánh Hòa',
    '28': 'Hòa Bình',
    '80': 'Cục CSGT đường bộ cấp',
    '29': 'Hà Nội',
    '30': 'Hà Nội',
    '31': 'Hà Nội',
    '32': 'Hà Nội',
    '33': 'Hà Nội',
    '40': 'Hà Nội',
    '81': 'Gia Lai',
    '34': 'Hải Dương',
    '82': 'Kon Tum',
    '35': 'Ninh Bình',
    '83': 'Sóc Trăng',
    '36': 'Thanh Hóa',
    '84': 'Trà Vinh',
    '37': 'Nghệ An',
    '85': 'Ninh Thuận',
    '38': 'Hà Tĩnh',
    '86': 'Bình Thuận',
    '43': 'TP. Đà Nẵng',
    '88': 'Vĩnh Phúc',
    '47': 'Đắk Lắk',
    '89': 'Hưng Yên',
    '48': 'Đắk Nông',
    '90': 'Hà Nam',
    '49': 'Lâm Đồng',
    '92': 'Quảng Nam',
    '41': 'TP. Hồ Chí Minh',
    '50': 'TP. Hồ Chí Minh',
    '51': 'TP. Hồ Chí Minh',
    '52': 'TP. Hồ Chí Minh',
    '53': 'TP. Hồ Chí Minh',
    '54': 'TP. Hồ Chí Minh',
    '55': 'TP. Hồ Chí Minh',
    '56': 'TP. Hồ Chí Minh',
    '57': 'TP. Hồ Chí Minh',
    '58': 'TP. Hồ Chí Minh',
    '59': 'TP. Hồ Chí Minh',
    '93': 'Bình Phước',
    '39': 'Đồng Nai',
    '60': 'Đồng Nai',
    '94': 'Bạc Liêu',
    '61': 'Bình Dương',
    '95': 'Hậu Giang',
    '62': 'Long An',
    '97': 'Bắc Cạn',
    '63': 'Tiền Giang',
    '98': 'Bắc Giang',
    '64': 'Vĩnh Long',
    '99': 'Bắc Ninh',
}

